### ISSUE TITLE
Standardize YAML rules between repositories

### ISSUE THREAD

**Issue by PowerSchill** [sous-chefs/meta#129]
### :speaking_head: Foreword

Thank for taking the time to fill this feature request fully. Without it we may not be able to , and the issue may be closed without resolution.

## :person_frowning: Problem Statement

Since we are enforcing yaml linting we should standardize the ruleset we apply to our repositories.

## :grey_question: Possible Solution

Adding a .yamlrc file to each repository will apply a standardized set of rules for repositories.

## :heavy_plus_sign: Additional context

A base .yamlrc file that I have used is below. Let's start with this and update/extend.

```yaml
extends: default
ignore: .kitchen/
rules:
  line-length:
    max: 120
    level: warning
```
