### ISSUE TITLE
Circle CI fails because Ubuntu 16.04 image

### ISSUE THREAD

**Issue by axl89** [sous-chefs/meta#133]
## :ghost: Brief Description

Circle CI uses Ubuntu 16 for the `dokken-single` job, and it fails because `curl -L https://omnitruck.chef.io/install.sh |
  sudo bash -s -- -c current -P chefdk` no longer supports Ubuntu 16.04. See [example](https://app.circleci.com/pipelines/github/axl89/ovh_the_bastion/47/workflows/84233b7d-fadb-4be1-9b95-04a0f11b6600/jobs/147/parallel-runs/0/steps/0-102).

## :pancakes: Cookbook version

Orb 2.1.1 with [this config](https://github.com/axl89/ovh_the_bastion/blob/main/.circleci/config.yml):

```yaml
---
version: 2.1
orbs:
  kitchen: sous-chefs/kitchen@2.1.1
jobs:
  cookstyle:
    docker:
      - image: chef/chefdk:4.9.17
    steps:
      - checkout
      - run: chef env --chef-license accept-silent
      - run: chef exec cookstyle .
  foodcritic:
    docker:
      - image: chef/chefdk:4.9.17
    steps:
      - checkout
      - run: chef env --chef-license accept-silent
      - run: chef exec foodcritic .

workflows:
  test:
    jobs:
      # Lint and Unit Test
      - kitchen/yamllint:
          name: lint-yaml
      - kitchen/dokken-single:
          name: dokken-single
          suite: default
      - cookstyle
      - foodcritic
```

## :woman_cook:  Chef-Infra Version

Not relevant, I believe.

## :tophat: Platform details

Circle CI.

## Steps To Reproduce

Try to launch a CI issue with the above yaml config.

## :police_car: Expected behavior

The CI job should pass. Maybe it's time to upgrade the image to Ubuntu 18.04 or 20.04.

## :heavy_plus_sign: Additional context

Thank you for the orb, it's really good. Hopefully we can fix this! :smile:
